name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: DeLaGuardo/setup-clojure@3.0
      with:
        tools-deps: '1.10.1.754'

    - name: Cache maven
      uses: actions/cache@v2.1.3
      env:
        cache-name: cache-maven
      with:
        path: ~/.m2
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Cache gitlibs
      uses: actions/cache@v2.1.3
      env:
        cache-name: cache-gitlibs
      with:
        path: ~/.gitlibs
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Install dependencies
      run: lein deps

    - name: generate python unit tests
      run: make -C python

    - name: Run clojure tests
      run: lein test

    - name: Run clojurescript node tests
      run: lein do clean, doo node node-test once
